name: PixelliteNetwork
author: Pixellite Studios
version: 1.0.0
description: Network management plugin
main: studio.pixellite.network.NetworkPlugin
api-version: 1.13
website: https://pixellite.studio/
depend: [helper, helper-redis]
softdepend: [PlaceholderAPI, LuckPerms]