name: PixelliteCore
author: Pixellite Studios
version: 1.1.0
description: Network management plugin
main: studio.pixellite.core.CorePlugin
api-version: 1.13
website: https://pixellite.studio/
depend: [helper, helper-redis]
softdepend: [PlaceholderAPI, LuckPerms]